config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root to: "items#index"
  resources :users, only: [:show, :update]
  resources :items do

    collection do
      get 'search'
    end
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '衣類・靴' },
    { id: 3, name: 'バッグ・アクセサリー・ファッション雑貨' },
    { id: 4, name: '家電' },
    { id: 5, name: '家具・インテリア' },
    { id: 6, name: 'ホビー・玩具・思い出の品' },
    { id: 7, name: '書籍・CD・DVD' },
    { id: 8, name: 'こども用品' },
    { id: 9, name: 'ストック品' },
    { id: 10, name: '生活雑貨' },
    { id: 11, name: '文具・工具' },
    { id: 12, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :user

  belongs_to :category
  belongs_to :let_go_way
  belongs_to :let_go_reason
  belongs_to :result

  has_one_attached :image

  with_options presence: true do
    validates :image
    validates :name
    validates :category_id
    validates :let_go_way_id
    validates :let_go_reason_id
    validates :result_id
  end

  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :category_id
    validates :let_go_way_id
    validates :let_go_reason_id
  end

  def self.search(search)
    if search != ''
      Item.where('name LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
end

app/models/let_go_reason.rb
class LetGoReason < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '不要になった' },
    { id: 3, name: '貰い物だけど使わない' },
    { id: 4, name: '使い勝手が悪い' },
    { id: 5, name: '壊れた' },
    { id: 6, name: '入れ替え' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/let_go_way.rb
class LetGoWay < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '自治体に従って処分' },
    { id: 3, name: '処分業者に依頼' },
    { id: 4, name: '買取業者に依頼' },
    { id: 5, name: '譲渡' },
    { id: 6, name: '寄付' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/result.rb
class Result < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '手離しても問題なかった' },
    { id: 3, name: '手離したことを後悔した' },
    { id: 4, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  has_many :items

  validates :nickname, presence: true

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: VALID_PASSWORD_REGEX, message: 'は半角の英字と半角の数字を含めて設定してください'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.includes(:user).order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    if @item.user_id == current_user.id
    else
      redirect_to root_path
    end
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(item_params)
    else
      render :edit
    end
  end

  def destroy
    if @item.user_id == current_user.id
      @item.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def search
    # params[:q]がnilではない且つ、params[:q][:name]がnilではないとき（商品名の欄が入力されているとき）
    # if params[:q] && params[:q][:name]と同じような意味合い
    if params[:q]&.dig(:name)
      # squishメソッドで余分なスペースを削除する
      squished_keywords = params[:q][:name].squish
      ## 半角スペースを区切り文字として配列を生成し、paramsに入れる
      params[:q][:name_cont_any] = squished_keywords.split(' ')
    end
    @q = Item.ransack(params[:q])
    @items = @q.result
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :category_id, :let_go_way_id, :let_go_reason_id, :result_id,
                                 :comment).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: [:update]

  protected

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:profile])
  end

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @items = current_user.items
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to _user_path(user_params)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :password, :encrypted_password, :profile).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<%= render "shared/second-header"%>

<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">断捨離の情報を編集</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
      </div>
      <%= image_tag @item.image.variant(resize: '500x500') %>
    </div>
    <%# /画像 %>
    <%# 名前 %>
    <div class="new-items">
      <div class="weight-bold-text">
        名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"名前（必須 40文字まで)", maxlength:"40" %>
    </div>
    <%# /名前 %>

    <%# 詳細情報 %>
    <div class="items-detail">
      <div class="weight-bold-text">詳細情報</div>
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        
          <div class="weight-bold-text">
            手離し方
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:let_go_way_id, LetGoWay.all, :id, :name, {}, {class:"select-box", id:"item-let-go-way"}) %>
      
          <div class="weight-bold-text">
            手離した理由
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:let_go_reason_id, LetGoReason.all, :id, :name, {}, {class:"select-box", id:"item-let-go-reason"}) %>

          <div class="weight-bold-text">
            手離した結果
            <span class="indispensable">後日選択可</span>
          </div>
          <%= f.collection_select(:result_id, Result.all, :id, :name, {}, {class:"select-box", id:"item-result"}) %>
        </div>
      </div>
      <%# /詳細情報 %>
      <%# コメント %>
      <div class="mew-items">
        <div class="items-explain">
          <div class="weight-bold-text">
            コメント
          <span class="indispensable">任意</span>
          </div>
          <%= f.text_area :comment, class:"items-text", id:"item-info", placeholder:"コメント" ,rows:"7" ,maxlength:"1000" %>
        </div>
      <div>
      <%# /コメント %>

      <%# 注意書き %>
      <div class="caution">
        <p class="sentence">
        様々な方の目に触れる可能性があります。
        </p>
        <p class="sentence">
          他の方を不快にする物品の登録はお控えください。
        </p>
        <p class="sentence">
          必ず、
          <a href="#">利用規約</a>
          をご確認の上でご登録ください。
        </p>
      </div>
      <%# /注意書き %>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "変更する" ,class:"sell-btn" %>
        <%=link_to 'もどる', item_path, class:"back-btn" %>
      </div>
    <%# /下部ボタン %>
    <% end %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>

<div class="py-4">
  <div class="container">
    <div id="main_visual" class="carousel slide" data-bs-ride="carousel">
      <ol class="carousel-indicators">
        <li data-bs-target="#main_visual" data-bs-slide-to="0" class="active"></li>
        <li data-bs-target="#main_visual" data-bs-slide-to="1"></li>
        <li data-bs-target="#main_visual" data-bs-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="img-fluid" src="../assets/slide_01.png" alt="片付け">
          <div class="carousel-caption d-note d-md-block">
            <h2 class="text-success bg-white bg-opacity-50"><strong>片付けなくちゃいけないのに…</strong></h2>
            <p class="text-success bg-white bg-opacity-50"><strong>片付けようと思っても「手離してしまって大丈夫か」、「ストックがなくて大丈夫か」と不安で結局手離せない。</strong></p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="img-fluid" src="../assets/slide_02.png" alt="増加">
          <div class="carousel-caption d-note d-md-block">
            <h2 class="text-success bg-white bg-opacity-50"><strong>いつの間にか増えていくもの…</strong></h2>
            <p class="text-success bg-white bg-opacity-50"><strong>捨てられないショップバッグ、ついつい増えていくポイントカード、通信販売の段ボール。気が付いたらたくさんある。</strong></p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="img-fluid" src="../assets/slide_03.png" alt="不用品">
          <div class="carousel-caption d-note d-md-block">
            <h2 class="text-success bg-white bg-opacity-50"><strong>今は使ってないけれど手離せない…</strong></h2>
            <p class="text-success bg-white bg-opacity-50"><strong>いつかまたやろうと思っている。思い出のものだから。高かったから。そんな理由で手離せないものがある。</strong></p>
          </div>
        </div>
      </div>

      <a class="carousel-control-prev" href="#main_visual" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">前に戻る</span>
      </a>
      <a class="carousel-control-next" href="#main_visual" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">次に進む</span>
      </a>
    </div>
  </div>
</div>



<!— コラム欄 —>
<div class="py-4">
  <section id="column">
    <div class="container">
      <div class="row">
    <div class="col-md-9">
      <h3>そんな悩みがあるのなら…まずはじめてみませんか？</h3>
      </div>
      <div class="col-md-10">
    <dl class="row">
      <dd class="col-md-9">■　1日1回、5分で良いので部屋の中を整えましょう。</dd>
      <dd class="col-md-9">■　今回片付けると決めた場所のものは全て出して持ち物の見直しましょう。</dd>
      <dd class="col-md-9">■　一度に片付ける場所を絞りましょう。いきなり全部やろうとすると収拾がつかなくなります。</dd>
    </dl>
      </div>
    </div>
</div>

<!— 閲覧・投稿欄 —>
<div class="py-4 bg-light">
  <section id="about">
    <div class="container">
      <div class="row mb-4">
        <div class="col-md-8 mb-3">
          <h3 class="mb-3">断捨離の記録を共有しませんか？</h3>
          <p>ものを手離すと決めたら、手離したものを投稿してあなたの断捨離の軌跡を残しませんか？</p>
          <p>あなたの記録が誰かの助けになるかもしれません。</p>
          <p>手離すのを迷ったら、ほかの人が手離したものをみてみましょう。</p>
          <p>何を、どうして、どんな方法で手離したのか参考になるかもしれません。</p>
          <ul>
            <li class="btn btn-info shadow"><%= link_to 'みんなの記録を見る', root_path(anchor: "view"), class: "text-dark text-decoration-none" %></li>
            <li class="btn btn-info shadow"><%= link_to '自分の記録を残す', new_item_path, class: "text-dark text-decoration-none" %></li>
            <li class="btn btn-info shadow"><%= link_to '検索', search_items_path, class: "text-dark text-decoration-none" %></li>
          </ul>
        </div>
        <div class="col-md-4">
          <img src="../assets/slide_05.png" alt="整理整頓" class="img-fluid">
        </div>
      </div>

      <div class=“row”>
        <div class=“col-md-4”>
          <div class="card mv-3">
            <img >

        </div>
        <div class=“col-md-4”>
        </div>
        <div class=“col-md-4”>
        </div>
      </div>
    </div>
  </section>
</div>

<%# 断捨離記録一覧 %>
  <div class='item-contents', id="view">
    <h2 class='title'>みんなの断捨離</h2>
    <div class="subtitle" >
      最新の断捨離
    </div>
    <ul class='item-lists'>

    <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item) do %>
        <div class='item-img-content'>
        <%= image_tag item.image.variant(resize: '500x500'), class: "item-img" if item.image.attached? %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span>手離し方：<%= item.let_go_way.name %></span>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>



<%= link_to(new_item_path, class: 'purchase-btn text-decoration-none') do %>
  <span class='purchase-btn-text '>記録する</span>
  <%= image_tag 'record_btn.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

<%= render "shared/footer" %>

app/views/items/new.html.erb
<%= render "shared/second-header"%>


<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">断捨離の情報を入力</h2>
    <%= form_with model: @item, id: 'new_post', local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      
      <div id="previews"></div>
      
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /画像 %>
    <%# 名前 %>
    <div class="new-items">
      <div class="weight-bold-text">
        名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"名前（必須 40文字まで)", maxlength:"40" %>
    </div>
    <%# /名前 %>

    <%# 詳細情報 %>
    <div class="items-detail">
      <div class="weight-bold-text">詳細情報</div>
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        
          <div class="weight-bold-text">
            手離し方
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:let_go_way_id, LetGoWay.all, :id, :name, {}, {class:"select-box", id:"item-let-go-way"}) %>
      
          <div class="weight-bold-text">
            手離した理由
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:let_go_reason_id, LetGoReason.all, :id, :name, {}, {class:"select-box", id:"item-let-go-reason"}) %>

          <div class="weight-bold-text">
            手離した結果
            <span class="indispensable">後日選択可</span>
          </div>
          <%= f.collection_select(:result_id, Result.all, :id, :name, {}, {class:"select-box", id:"item-result"}) %>
        </div>
      </div>
      <%# /詳細情報 %>
      <%# コメント %>
      <div class="mew-items">
        <div class="items-explain">
          <div class="weight-bold-text">
            コメント
          <span class="indispensable">任意</span>
          </div>
          <%= f.text_area :comment, class:"items-text", id:"item-info", placeholder:"コメント" ,rows:"7" ,maxlength:"1000" %>
        </div>
      <div>
      <%# /コメント %>

      <%# 注意書き %>
      <div class="caution">
        <p class="sentence">
        様々な方の目に触れる可能性があります。
        </p>
        <p class="sentence">
          他の方を不快にする物品の登録はお控えください。
        </p>
        <p class="sentence">
          必ず、
          <a href="#">利用規約</a>
          をご確認の上でご登録ください。
        </p>
      </div>
      <%# /注意書き %>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "登録する" ,class:"sell-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
    </div>
  </div>
</div>

app/views/items/search.html.erb
<%= render "shared/header" %>
<div class="search">
  <h3 class='title'>検索ページ</h3>
  <div>
    <%= search_form_for @q, url: search_items_path, html: {id: "detailed-search-form"} do |f| %>
      <div class="search-field">
        <%= f.label :category_id_in, '【カテゴリー】' %>
        <br>
        <%= f.collection_select(:category_id_in, Category.all, :id, :name, include_blank: false) %>
      </div>
      <input type="submit" value="検索" class="search-button">
      <%= f.submit :submit, id: "q_submit", style: "display: none;" %>
    <% end %>
  </div>
  <div class='item-contents' id="view">
    <h2 class='title'>検索結果一覧</h2>
    <ul class='item-lists' id="detailed-search-result">
      <% @items.each do |item| %>
        <li class='list'>
          <div class="posted-content">
            <%= image_tag item.image.variant(resize: '500x500'), class: "item-img" if item.image.attached? %><br>
            <%= item.name%><br>
            <%= link_to '詳細', item_path(item.id)%>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>


<%= render "shared/footer" %>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 断捨離記録の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @item.image.variant(resize: '500x500') ,class:"item-box-img" %>
    </div>

    <div class="item-explain-box">
      <span><%= @item.comment %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">手離し方</th>
          <td class="detail-value"><%= @item.let_go_way.name %></td>
        </tr>
        <tr>
          <th class="detail-item">手離した理由</th>
          <td class="detail-value"><%= @item.let_go_reason.name %></td>
        </tr>
        <tr>
          <th class="detail-item">手離した結果</th>
          <td class="detail-value"><%= @item.result.name %></td>
        </tr>
      </tbody>
    </table>

    <% if user_signed_in? %>
      <% if current_user.id == @item.user_id %>
      <ul>
        <li class="btn btn-lg btn-info shadow mx-5"><%= link_to "記録の編集", edit_item_path, method: :get, class: "text-dark text-decoration-none" %></li>
        <li class="btn btn-lg btn-danger shadow mx-5"><%= link_to "削 除", item_path, method: :delete, class: "text-dark text-decoration-none" %></li>
      <ul>
      <% end %>
    <% end %>
  <%# /商品の概要 %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SekaraDanshari</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-4 bg-dark bg-gradient text-light">
  <div class="container text-center">
    <ul class="nav justify-content-center mb-3">
      <li class="nav-item">
        <a class="nav-link" href="#">ホーム</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">新着</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">利用規約</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">プライバシーポリシー</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="contact.html">お問い合わせ</a>
      </li>
    </ul>
    <p>
      <small>Copyright &copy;2022 sekara　断捨離, All Rights Reserved.</small>
    </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="py-4">
  <div class="container text-center">
    <h1 class="mw-100">
      <%= image_tag 'clean_01.png' , size: '50x50'%>
      <%= link_to 'sekara　断捨離', root_path, class: "text-dark text-decoration-none" %>
      <%= image_tag 'clean_02.png' , size: '50x50' %>
    </h1>
  </div>
</header>

<nav class="navbar navbar-expand-md navbar-dark bg-dark bg-gradient sticku-top">
  <div class="container">
    <!-- ↓あとで[a]は全てrootリンクに変更 -->
    <%= link_to 'ホーム', root_path, class: "navbar-brad"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="cllapse" data-bs-target="#navbar-content" aria-controls="nvbar-content" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-content">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to '最新の断捨離記録', root_path(anchor: "view"), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">手離し方参考リンク集</a>
        </li>
      </ul>

      <ul class="navbar-nav">
        <div>
        <% if user_signed_in? %>
          <li class="btn btn-light mx-3"><%=link_to current_user.nickname, "/users/#{current_user.id}", class: "text-dark text-decoration-none" %></li>
          <li class="btn btn-light"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "text-dark text-decoration-none" %></li>
        <% else %>
          <li class="btn btn-light mx-3"><%=link_to '新規登録', new_user_registration_path, class: "text-dark text-decoration-none" %></li>
          <li class="btn btn-light"><%= link_to 'ログイン', new_user_session_path, class: "text-dark text-decoration-none" %></li>
        <% end %>
        </div>
      </ul>
    </div>
    
  </div>
</nav>

<div class="mx-3 my-3">
  <%= search_form_for Item.ransack(params[:q]), url: search_items_path, html: {class: "detiled-search-form"} do |f| %>
      <%= f.text_field :name, placeholder: '物品名から探す', class: 'input-box' %>
      <br>
      <%= f.label :submit do %>
        <input type="submit" value="検索" class="search-button">
        <%= f.submit :submit, id: "q_submit", style: "display: none;"%>
      <% end %>
      <%= link_to '検索ページへ進む', search_items_path, class: "search-button-another text-dark text-decoration-none" %>
    <% end %>

</div>

app/views/shared/_second-header.html.erb
<header class="py-4">
  <div class="container text-center">
    <h1 class="mw-100">
      <%= image_tag 'clean_01.png' , size: '50x50'%>
      <%= link_to 'sekara　断捨離', root_path, class: "text-dark text-decoration-none" %>
      <%= image_tag 'clean_02.png' , size: '50x50' %>
    </h1>
  </div>
</header>

<nav class="navbar navbar-expand-md navbar-dark bg-dark bg-gradient sticku-top">
  
</nav>

app/views/users/show.html.erb
<%= render "shared/second-header"%>

<h2 class="mx-2">
  <%= "#{@user.nickname}さんの情報" %>
  <% if user_signed_in? %>
  <div class="btn btn-lg btn-light shadow mx-5"><%= link_to "ユーザー情報の編集", edit_user_registration_path, method: :get, class: "text-dark text-decoration-none" %></div>
  <% end %>
</h2>
<table class="table">
  <tbody>
    <tr>
      <th class="table__col1">名前</th>
      <td class="table__col2"><%= @user.nickname %></td>
    </tr>
    <tr>
      <th class="table__col1">プロフィール</th>
      <td class="table__col2"><%= @user.profile %></td>
    </tr>
  </tbody>
</table>


<div class='item-contents', id="view">
  <h2 class='title'><%= @nickname %>さんのマイページ</h2>
    <ul class='item-lists'>
    <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item) do %>
        <div class='item-img-content'>
        <%= image_tag item.image.variant(resize: '500x500'), class: "item-img" if item.image.attached? %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span>手離し方：<%= item.let_go_way.name %></span>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<%= render "shared/footer" %>